- name: make this server a dank selfhosting machine
  hosts: local
  vars_files:
    - vars.yml
  roles:
    # Explicity specify ordering of all roles and dependencies here. Sadly,
    # the the version of ansible on OpenBSD 6.4 just blindly executes roles
    # specified in meta dependencies multiple times.
    - { role: base,       tags: ['base']       }
    - { role: dkim,       tags: ['dkim']       }
    - { role: nsd,        tags: ['nsd']        }
    - { role: httpd,      tags: ['httpd']      }
    - { role: acme,       tags: ['acme']       }
    - { role: nginx,      tags: ['nginx']      }
    - { role: dovecot,    tags: ['dovecot']    }
    - { role: smtpd,      tags: ['smtpd']      }
    - { role: spamd,      tags: ['spamd']      }
    - { role: postgresql, tags: ['postgresql'] }
    - { role: ldapd,      tags: ['ldapd']      }
    - { role: prosody,    tags: ['prosody']    }
    - { role: znc,        tags: ['znc']        }
    - { role: php,        tags: ['php']        }
    - { role: ttrss,      tags: ['ttrss']      }
    - { role: synapse,    tags: ['synapse']    }
    - { role: gitea,      tags: ['gitea']      }
    - { role: davical,    tags: ['davical']    }
    - { role: dank,       tags: ['dank']       }
