---
- name: restart prosody
  service:
    name: prosody
    state: restarted

- name: reload prosody
  command: prosodyctl reload
  become_user: _prosody

- name: reload nginx
  service:
    name: nginx
    state: reloaded
