- name: enable nginx vhost
  copy:
    content: |
      server {
        listen      443 ssl http2;
        listen      [::]:443 ssl http2;
        {% if bare | default(false) %}
        server_name {{ domain }};
        {% else %}
        server_name {{ vhost | default(name + "." + domain) }};
        {% endif %}
        client_max_body_size {{ max_body_size | default('5m') }};
        location / {
          {% if port is defined %}
          proxy_pass  http://127.0.0.1:{{ port }}/;
          {% elif socket is defined %}
          proxy_pass  http://unix:{{ socket }}:/;
          {% endif %}
          proxy_set_header Host              $host;
          proxy_set_header X-Forwarded-For   $remote_addr;
          proxy_set_header X-Forwarded-Proto https;
          proxy_http_version 1.1;
        }
        {% if bare | default(false) %}
        location /.well-known {
          {% if port is defined %}
          proxy_pass  http://127.0.0.1:{{ port }}/;
          {% elif socket is defined %}
          proxy_pass  http://unix:{{ socket }}:/;
          {% endif %}
          proxy_set_header Host              $host;
          proxy_set_header X-Forwarded-For   $remote_addr;
          proxy_set_header X-Forwarded-Proto https;
          proxy_http_version 1.1;
          add_header Access-Control-Allow-Origin *;
        }
        {% endif %}
      }
    dest: /etc/nginx/sites/{{ "bare" if (bare | default(false)) else name }}.conf
  notify: reload nginx
