# store DKIM records into dkim_records variable
---
- name: read dkim records
  shell: cat {{ dkim_home }}/*.txt
  register: cat_dkim_records
  changed_when: False

- name: set dkim records
  set_fact:
    dkim_records: '{{ cat_dkim_records.stdout }}'
