---
syslog_log_files:
  - nsd
  - postgresql
  - prosody
  - spamd
  - httpd
  - php-fpm
  - relayd
  - turnserver
basedn: "{{ domain.split('.') | map('regex_replace', '(.*)', 'dc=\\1') | join(',') }}"
