---
- name: reload httpd
  service:
    name: httpd
    state: reloaded

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart php-fpm
  service:
    name: php72_fpm
    state: restarted
