---
- name: install packages
  openbsd_pkg:
    name: dkimproxy
    state: installed

- name: generate dkimproxy_out.conf
  template:
    src: dkimproxy_out.conf.j2
    dest: /etc/dkimproxy_out.conf
  notify: restart dkimproxy

- name: create dkim directory
  file:
    path: '{{ dkim_home }}'
    mode: 0755
    state: directory

- name: create dkim private directory
  file:
    path: '{{ dkim_home }}/private'
    owner: root
    group: _dkimproxy
    mode: 0750
    state: directory

- name: generate dkim keys
  include: dkim_key.yml
  vars:
    selector: '{{ item.selector }}'
    subdomain: '{{ item.subdomain if item.subdomain is defined else omit }}'
  with_items:
    - { selector: dkim }
    - { selector: cal, subdomain: dav }

- name: enable and start daemon
  service:
    name: dkimproxy_out
    enabled: yes
    state: started
